name: flutter_markdown_selectionarea
description: SelectionArea and additional Semantics support
repository: https://github.com/adrianjagielak/flutter_markdown_selectionarea
issue_tracker: https://github.com/adrianjagielak/flutter_markdown_selectionarea/issues
version: 0.6.14+4

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  markdown: ^7.0.0
  meta: ^1.3.0
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
